# Generated by Django 5.2.11 on 2026-02-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=100)),
                ('granted_by', models.CharField(choices=[('subscription', 'Subscription'), ('trial', 'Trial'), ('manual', 'Manual Grant'), ('promo', 'Promotion'), ('referral', 'Referral'), ('employee', 'Employee Perk')], default='subscription', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=255)),
                ('usage_limit', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'entitlements',
                'indexes': [models.Index(fields=['customer', 'feature', 'is_active'], name='entitlement_custome_bbb0a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'feature', 'subscription'), name='unique_entitlement_per_subscription')],
            },
        ),
    ]
