# Generated by Django 5.2.11 on 2026-02-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('subscription_new', 'New Subscription'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_upgrade', 'Subscription Upgrade'), ('subscription_downgrade', 'Subscription Downgrade'), ('one_time', 'One-Time Purchase')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed')], db_index=True, default='paid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_name', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('dispute_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounts.customer')),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='purchases_custome_1609de_idx'), models.Index(fields=['customer', 'purchase_type'], name='purchases_custome_453c18_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_invoice_id', ''), _negated=True), fields=('stripe_invoice_id', 'stripe_price_id'), name='unique_purchase_per_invoice_line'), models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id', ''), _negated=True), fields=('stripe_checkout_session_id',), name='unique_purchase_per_checkout_session')],
            },
        ),
    ]
