# Generated by Django 5.2.11 on 2026-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('canceled', 'Canceled')], max_length=12),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('canceled', 'Canceled')], max_length=12),
        ),
    ]
