# Generated by Django 5.2.11 on 2026-02-04 20:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["price_monthly"]},
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="display_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_product_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "current_period_end"],
                name="subscriptio_user_id_adcfe3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="subscriptio_is_acti_4b16f2_idx",
            ),
        ),
    ]
